#!/bin/sh


start() {
  /bin/day_night_switch.sh &
}

stop() {
echo 0;
}


case "$1" in
	start|stop)
		$1
		;;

	restart)
		stop
		sleep 3
		start
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac
